[tool.poetry]
name = "scint"
version = "0.1.0"
description = "Cllaborative intelligence"
authors = ["Tim Kaechle <timothy.kaechle@me.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "scint"}]

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
openai = "^0.27.8"
loguru = "^0.7.0"
rich = "^13.5.2"
requests = "^2.31.0"
tenacity = "^8.2.3"
asyncio = "^3.4.3"
env = "^0.1.0"
google-api-python-client = "^2.97.0"
python-dotenv = "^1.0.0"
rethinkdb = "^2.4.9"
typesense = "^0.16.0"
meilisearch = "^0.28.2"
fastapi = "^0.101.1"
psycopg2 = "^2.9.7"
pytest = "^7.4.1"
sentence-transformers = "^2.2.2"
nltk = "^3.8.1"
scrapy = "^2.10.1"
scrapy-splash = "^0.9.0"
wikipedia-api = "^0.6.0"
scipy = "^1.11.2"
uvicorn = "^0.23.2"
pydantic = "^2.3.0"
tiktoken = "^0.5.1"
aioconsole = "^0.6.2"
watchdog = "^3.0.0"
spacy = "^3.6.1"
tree-sitter = "^0.20.2"
gensim = "^4.3.2"
pytz = "^2023.3.post1"
discord = "^2.3.2"
llmonitor = "^0.0.7"
httpx = {extras = ["cli"], version = "^0.25.0"}
xdg-base-dirs = "^6.0.1"
edgedb = "^1.7.0"
pandas = "^2.1.1"
redis = "^5.0.1"
aiohttp = "^3.8.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
