[tool.poetry]
name = "scint"
version = "0.3.9"
description = ""
authors = ["Tim Kaechle <timothy.kaechle@me.com>"]
readme = "README.md"
packages = [{ include = "scint" }]

[tool.poetry.dependencies]
python = "^3.12"
aiohttp = "^3.9.1"
python-dotenv = "^1.0.0"
openai = { extras = ["datalib"], version = "^1.17.0" }
anthropic = "^0.26.0"
aiofiles = "^23.2.1"
redis = "^5.0.3"
websockets = "^12.0"
meilisearch = "^0.31.0"
libmagic = "^1.0"
python-magic = "^0.4.27"
tree-sitter = "0.21.3"
pytest = "^8.2.2"
pytest-cov = "^5.0.0"
meilisearch-python-sdk = "^2.10.1"
uvicorn = { extras = ["standard"], version = "^0.30.1" }
falcon = "^3.1.3"
pydantic = "^2.8.2"
pydantic-settings = "^2.3.4"

[tool.poetry.scripts]
scint = "app.server:run"

[tool.pyright]
venvPath = "/Users/kaechle/Library/Caches/pypoetry/virtualenvs"
venv = "test-0DJbXm4h-py3.12"
reportMissingImports = true
reportSyntaxErrors = true
reportMissingTypeStubs = false
reportUnknownVariableType = false
reportUnknownMemberType = false
reportUnknownArgumentType = false
reportUnknownLambdaType = true
reportMissingModuleSource = true
reportGeneralTypeIssues = false
typeCheckingMode = "off"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
