[project]
name = "scint"
version = "0.1.0"
description = "Add your description here"
readme = { file = "README.md", content-type = "text/markdown" }
license = { text = "MIT License" }
requires-python = ">=3.10"
dependencies = [
    "aiofiles>=24.1.0",
    "aiohttp>=3.10.10",
    "anthropic>=0.39.0",
    "meilisearch-python-sdk>=3.6.1",
    "meilisearch>=0.31.6",
    "openai>=1.55.2",
    "psycopg2>=2.9.10",
    "python-dotenv>=1.0.1",
    "pyyaml>=6.0.2",
    "redis>=5.2.0",
    "tree-sitter>=0.23.2",
    "tree-sitter-python>=0.23.3",
    "uvicorn>=0.32.0",
    "chonkie>=0.1.2",
    "numpy>=2.1.3",
    "ruff>=0.8.0",
    "rich>=13.9.4",
    "nltk>=3.9.1",
    "websockets>=14.1",
]

[tool.poetry]
name = "scint"
version = "0.1.0"
description = ""
authors = ["Tim Kaechle <timothy.kaechle@me.com>"]
readme = "README.md"
packages = [{ include = "src" }]

[tool.poetry.dependencies]
python = ">=3.10"

[tool.pyright]
venvPath = ".venv"
venv = "."
reportMissingImports = true
reportSyntaxErrors = true
reportMissingTypeStubs = false
reportUnknownVariableType = false
reportUnknownMemberType = false
reportUnknownArgumentType = false
reportUnknownLambdaType = "none"
reportMissingModuleSource = true
reportGeneralTypeIssues = false
typeCheckingMode = "off"

[tool.ruff.lint]
ignore = ["E731"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
