[tool.poetry]
name = "scint"
version = "0.1.0"
description = "Stateful, collaborative intelligence"
authors = ["Tim Kaechle <timothy.kaechle@me.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "base"}]

[tool.poetry.dependencies]
python = "^3.11"
openai = "^0.27.8"
loguru = "^0.7.0"
rich = "^13.5.2"
requests = "^2.31.0"
tenacity = "^8.2.3"
asyncio = "^3.4.3"
terminusdb-client = "^10.2.4"
env = "^0.1.0"
google-api-python-client = "^2.97.0"
python-dotenv = "^1.0.0"
rethinkdb = "^2.4.9"
typesense = "^0.16.0"
meilisearch = "^0.28.2"
fastapi = "^0.101.1"
psycopg2 = "^2.9.7"
pytest = "^7.4.1"
sentence-transformers = "^2.2.2"
nltk = "^3.8.1"
scrapy = "^2.10.1"
scrapy-splash = "^0.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
