[tool.poetry]
name = "scint"
version = "0.5.0"
description = ""
authors = ["Tim Kaechle <timothy.kaechle@me.com>"]
readme = "README.md"
packages = [{ include = "scint" }]

[tool.poetry.dependencies]
python = "^3.12"
python-dotenv = "^1.0.0"
openai = { extras = ["datalib"], version = "^1.17.0" }
anthropic = "^0.26.0"
aiofiles = "^23.2.1"
redis = ">=4.1.4,<5.0.0"
websockets = "^13.0"
spacy = "^3.7.5"
pytest = "^8.2.2"
meilisearch-python-sdk = "^3.2.0"
sqlalchemy = "^2.0.31"
uvicorn = { extras = ["standard"], version = "^0.30.1" }
falcon = "^3.1.3"
pydantic = "^2.8.2"
pandas = "^2.2.2"
numpy = "^2.1.0"
tree-sitter = "0.21.3"
scipy = "^1.14.1"
aiohttp = "^3.10.5"
psycopg2 = "^2.9.9"
pgvector = "^0.3.2"
jinja2 = "^3.1.4"
gears-cli = "^1.2.0"

[tool.pytest]
testpaths = ["tests"]
addopts = "--import-mode=importlib"
pythonpath = ["."]

[tool.poetry.scripts]
scint = "uvicorn scint.app:server --reload --log-level info --port 8000"

[tool.pyright]
venvPath = ".venv"
venv = "."
reportMissingImports = true
reportSyntaxErrors = true
reportMissingTypeStubs = false
reportUnknownVariableType = false
reportUnknownMemberType = false
reportUnknownArgumentType = false
reportUnknownLambdaType = "none"
reportMissingModuleSource = true
reportGeneralTypeIssues = false
typeCheckingMode = "off"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
