[tool.poetry]
name = "scint"
version = "0.3.9"
description = ""
authors = ["Tim Kaechle <timothy.kaechle@me.com>"]
readme = "README.md"
packages = [{ include = "scint" }]

[tool.poetry.dependencies]
python = "^3.12"
uvicorn = "^0.29.0"
loguru = "^0.7.2"
aiohttp = "^3.9.1"
python-dotenv = "^1.0.0"
openai = { extras = ["datalib"], version = "^1.17.0" }
anthropic = "^0.26.0"
aiofiles = "^23.2.1"
redis = "^5.0.3"
websockets = "^12.0"
pydantic = "^2.7.1"
fastapi = "^0.111.0"
libmagic = "^1.0"
python-magic = "^0.4.27"
tree-sitter = "0.21.3"
pydantic-settings = "^2.2.1"
aiostream = "^0.6.1"
spacy = "^3.7.5"
pytest = "^8.2.2"
pytest-cov = "^5.0.0"
meilisearch-python-sdk = "^2.10.1"

[tool.poetry.scripts]
scint = "scint.server:run"

[tool.pyright]
venvPath = "."
venv = ".venv"
reportMissingImports = true
reportSyntaxErrors = true
reportMissingTypeStubs = false
reportUnknownVariableType = false
reportUnknownMemberType = false
reportUnknownArgumentType = false
reportUnknownLambdaType = true
reportMissingModuleSource = true
reportGeneralTypeIssues = false
typeCheckingMode = "off"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
