[tool.poetry]
name = "scint"
version = "0.3.9"
description = ""
authors = ["Tim Kaechle <timothy.kaechle@me.com>"]
readme = "README.md"
packages = [{ include = "scint" }]

[tool.poetry.dependencies]
python = "^3.12"
uvicorn = "^0.29.0"
loguru = "^0.7.2"
tenacity = "^8.2.3"
aiohttp = "^3.9.1"
python-dotenv = "^1.0.0"
openai = { extras = ["datalib"], version = "^1.17.0" }
anthropic = "^0.26.0"
aiofiles = "^23.2.1"
redis = "^5.0.3"
websockets = "^12.0"
meilisearch = "^0.31.0"
pydantic = "^2.7.1"
rethinkdb = "^2.4.10.post1"
fastapi = "^0.111.0"
libmagic = "^1.0"
python-magic = "^0.4.27"
tree-sitter = "^0.22.3"
pydantic-settings = "^2.2.1"
discord = "^2.3.2"

[tool.poetry.scripts]
scint = "scint.server:run"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
