[tool.poetry]
name = "scint"
version = "0.3.2"
description = "Structured Composable Intelligence"
authors = ["Tim Kaechle <timothy.kaechle@me.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "scint"}]

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
openai = "^0.27.8"
loguru = "^0.7.0"
tenacity = "^8.2.3"
asyncio = "^3.4.3"
env = "^0.1.0"
google-api-python-client = "^2.97.0"
fastapi = "^0.101.1"
pytest = "^7.4.1"
wikipedia-api = "^0.6.0"
uvicorn = "^0.23.2"
pydantic = "^2.3.0"
tiktoken = "^0.5.1"
aioconsole = "^0.6.2"
spacy = "^3.6.1"
tree-sitter = "^0.20.2"
discord = "^2.3.2"
xdg-base-dirs = "^6.0.1"
aiohttp = "^3.8.5"
python-dotenv = "^1.0.0"
sqlalchemy = "^2.0.22"
psycopg2 = "^2.9.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
